# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efcb6fb819059bdb9502c93ca38e875cf6ee16e2768a5b35a0bf1876ccdd966491d6125251aa5f36756a02fb82528ae288dae42328d9a819c02b942dd7de332a

test:
  secret_key_base: 63d1c93326f9c56df43f4f05cc206aaa2dd8d2ef5697246072a608be39e1d440cefb004c6399f1a31450e553ed1257294b04e40ecc224afef836818ca6146a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
